spring.application.name=backend

# 1. Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ten_database_cua_ban
spring.datasource.username=postgres
spring.datasource.password=mat_khau_postgres_cua_ban
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình Hibernate và JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
